{{- if .Values.auth.externalSecret.create }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-authjs" (include "code-kebab.fullname" .)) .Values.auth.externalSecret.name }}
  labels:
    {{- include "code-kebab.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.auth.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.auth.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.auth.externalSecret.secretStoreRef.name }}
  target:
    name: {{ default (printf "%s-authjs" (include "code-kebab.fullname" .)) .Values.auth.externalSecret.target.name }}
    creationPolicy: {{ .Values.auth.externalSecret.target.creationPolicy }}
  data:
    - secretKey: {{ .Values.auth.externalSecret.secretKey }}
      remoteRef:
        key: {{ .Values.auth.externalSecret.remoteRef.key }}
        {{- with .Values.auth.externalSecret.remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
    {{- range .Values.auth.externalSecret.extraData }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
