{{- if .Values.gateway.clusterIssuer.cloudflare.externalSecret.create }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.name }}
  namespace: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.namespace }}
  labels:
    {{- include "code-kebab.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.target.name }}
    creationPolicy: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.target.creationPolicy }}
  data:
    - secretKey: {{ .Values.gateway.clusterIssuer.cloudflare.apiTokenSecretRef.key }}
      remoteRef:
        key: {{ .Values.gateway.clusterIssuer.cloudflare.externalSecret.remoteRef.key }}
        {{- with .Values.gateway.clusterIssuer.cloudflare.externalSecret.remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
{{- end }}
