apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azurekv-cluster-secret-store
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      tenantId: 8333ad64-f386-4900-9627-cb5654976d75
      vaultUrl: "https://code-kebab.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azurekv-sp-secret
          key: ClientID
          namespace: external-secrets
        clientSecret:
          name: azurekv-sp-secret
          key: ClientSecret
          namespace: external-secrets
  conditions:
    - namespaces:
        - kube-system
        - cert-manager
        - external-secrets
        - code-kebab
